### ISSUE TITLE
We need a view for creating a new question

### ISSUE THREAD

**Issue by timlinux** [kartoza/crowdpinion#1]
![image](https://user-images.githubusercontent.com/178003/52693943-dcdfae00-2f70-11e9-84f5-181d3e7cd9bf.png)

This can be the landing page for the site for now.

When you submit the form it will give you a unique URL, nice and short e.g.

http://crowdpinion.kartoza.com/1

Which will be displayed with a message like this:

------------
Thank you for submitting your crowdpinion question! Ask your crowd to go here to share their thoughts:

http://crowdpinion.kartoza.com/1

Then view the results at 

http://crowdpinion.kartoza.com/results/1

------------

**Comment by anitanh** [comment]
progress so far, the UI is still basic:

Landing page:
![screenshot from 2019-02-14 10-12-42](https://user-images.githubusercontent.com/26101337/52760978-2b11b180-3044-11e9-8793-01199c5e2fa5.png)
![peek 2019-02-14 10-13](https://user-images.githubusercontent.com/26101337/52761021-54324200-3044-11e9-8444-61170d6bebe0.gif)

Answer page for participants:
![screenshot from 2019-02-14 10-15-23](https://user-images.githubusercontent.com/26101337/52760988-349b1980-3044-11e9-8afc-25fd7e7dea77.png)

![peek 2019-02-14 10-18](https://user-images.githubusercontent.com/26101337/52761033-5e544080-3044-11e9-8621-7c5b87f113f6.gif)

Admin:
![screenshot from 2019-02-14 10-18-59](https://user-images.githubusercontent.com/26101337/52760992-3a90fa80-3044-11e9-9d6a-321607310202.png)
![screenshot from 2019-02-14 10-19-06](https://user-images.githubusercontent.com/26101337/52760993-3b299100-3044-11e9-84d4-2a2f63afc661.png)
